version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: seo-audit-postgres
    environment:
      POSTGRES_DB: seo_audit
      POSTGRES_USER: seo_audit
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U seo_audit -d seo_audit"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - seo-audit-network

  adminer:
    image: adminer:4.8.1
    container_name: seo-audit-adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - seo-audit-network

  redis:
    image: redis:7-alpine
    container_name: seo-audit-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - seo-audit-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  seo-audit-network:
    driver: bridge
