"""add_user_id_to_audits

Revision ID: 40e55d3fe354
Revises: add_detected_tools_field
Create Date: 2025-09-07 01:43:31.793367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40e55d3fe354'
down_revision = 'add_detected_tools_field'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audits', sa.Column('user_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_audits_user_id'), 'audits', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audits_user_id'), table_name='audits')
    op.drop_column('audits', 'user_id')
    # ### end Alembic commands ###
