"""Add detected_tools field to audits table

Revision ID: add_detected_tools_field
Revises: dbdfe8ce2562
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_detected_tools_field'
down_revision = 'dbdfe8ce2562'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audits', sa.Column('detected_tools', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audits', 'detected_tools')
    # ### end Alembic commands ###
