"""Add top_keywords field to audits table

Revision ID: dbdfe8ce2562
Revises: 0e89c58b9d7b
Create Date: 2025-09-03 02:15:03.026346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbdfe8ce2562'
down_revision = '0e89c58b9d7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audits', sa.Column('top_keywords', sa.JSON(), nullable=True))
    # Note: Skipping UUID column changes as SQLite doesn't support ALTER COLUMN
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audits', 'top_keywords')
    # Note: Skipping UUID column changes as SQLite doesn't support ALTER COLUMN
    # ### end Alembic commands ###
